---
title: "stringtie_ISAR"
output: html_document
---

```{r}
library(IsoformSwitchAnalyzeR)
library(tidyverse)
```


this doesn't work, it's too big. see readme
```{r}
stringtie <- importIsoformExpression(parentDir = "all_out/", readLength = 76)

myDesign <- data.frame(sampleID =  c("D6K20d2", "D6K20d3",  "D6K20W1", "D6Krw1", "D6Krw3", "D6L20d1", "D6L20d2", "D6L20d3", "D6L20W1", "D6L20W2", "D6L20W3", "D6L40d1", "D6L40d2", "D6L40d3", "D6L40W1", "D6L40W2", "D6L40W3", "D6L60d1", "D6L60d2", "D6L60d3", "D6L60W1", "D6L60W2", "D6L60W3", "D6Lrw1", "D6Lrw2", "D6Lrw3", "D7K20d2", "D7K20d5", "D7K20W1", "D7K20W2", "D7K40d1", "D7K40d2", "D7K40W2", "D7K40W3", "D7K40W4", "D7K60d1", "D7K60d2", "D7K60d3", "D7K60W2", "D7K60W3", "D7K60W4",  "D7Krw2"), condition = rep(c("K20d", "K20w", "Krw", "L20d", "L20w", "L40d", "L40w", "L60d", "L60w", "Lrw", "K20d", "K20w", "K40d", "K40w", "K60d", "K60w", "Krw"), times = c(2, 1, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 1)))
myDesign$sampleID <- as.factor(myDesign$sampleID)
myDesign$condition <- as.factor(myDesign$condition)
aSwitchList <- importRdata(isoformCountMatrix = stringtie$counts, isoformRepExpression = stringtie$abundance, designMatrix = myDesign, isoformExonAnnoation = "C:/Users/hasna/Documents/MSc_project/stringtie/all_merged_stringtie.gtf")
```

